//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserTask.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class usertaskEntities : DbContext
    {
        public usertaskEntities() : base("metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=System.Data.SqlClient;provider connection string='Server=removedForSecurityPurposes;Database=removedForSecurityPurposes;persist security info=True;user id=UserTaskUser;password=removedForSecurityPurposes; MultipleActiveResultSets=True;App=EntityFrameworkTrustServerCertificate=True'")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Priority_level> Priority_level { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Task_status> Task_status { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
