//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserTask.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int t_id { get; set; }
        public string t_title { get; set; }
        public string t_description { get; set; }
        public Nullable<System.DateTime> t_due_date { get; set; }
        public int t_priority_level { get; set; }
        public int t_status { get; set; }
        public int t_user_id { get; set; }
    
        public virtual Priority_level Priority_level { get; set; }
        public virtual Task_status Task_status { get; set; }
        public virtual Users Users { get; set; }
    }
}
